backend:
  name: git-gateway
  branch: main

media_folder: 'assets/images'

collections:
  - name: 'posts'
    label: 'Events'
    folder: 'posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Summary',
          name: 'summary',
          widget: 'text',
          default: 'Short description of the post',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'social'
    label: 'Social'
    folder: '_data'
    create: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Class', name: 'iconClass', widget: 'string' }
      - { label: 'Url', name: 'url', widget: 'string' }
