backend:
  name: git-gateway
  branch: main

media_folder: 'assets/images'

collections:
  - name: 'posts'
    label: 'Events'
    folder: 'posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Summary',
          name: 'summary',
          widget: 'text',
          default: 'Short description of the post',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Main page - Email and phone number'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Phone Number', name: 'phoneNumber', widget: 'string' }
      - label: 'About page'
        name: 'about'
        file: 'posts/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Picture', name: 'thumbnail', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Social links'
        name: 'socialLinks'
        file: '_data/social.json'
        fields:
          - label: 'List of social links'
            name: 'social'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Icon', name: 'iconClass', widget: 'string' }
              - { label: 'Link', name: 'url', widget: 'string' }
